algunos recursos
gophers-mx/recursos pull request #2
Opened 2021-02-07 06:32 UTC by zeroidentidad

agrego algunos recursos que quizá sean útiles 👍🏽

2021-02-08 01:18 UTC, zeroidentidad commented
versión blog: https://wp.me/p1baRR-Hc

2021-02-09 01:28 UTC, danvergara requested changes

2021-02-09 01:28 UTC, danvergara commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
Creo que deberíamos tener una sección para e-books, porque creo que el recurso de apuntes es más un libro en línea y yo estoy por agregar [lear go with tests](https://quii.gitbook.io/learn-go-with-tests/) que también funciona como uno. Qué te parece?

2021-02-09 03:37 UTC, zeroidentidad commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
como te parezca es cosa de que se aprobara el PR y agregaras tus cambios, ya es pedo de @da-edra que revise los cambios :v

2021-02-09 04:08 UTC, 4k1k0 commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
¿Cuál sería la diferencia entre una tabla de ebooks y la actual de libros?

2021-02-09 04:14 UTC, zeroidentidad commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
@4k1k0 según o de acuerdo a lo mencionado por @danvergara son tipos gitbooks o libros web como una wiki de temas de Golang ejemplos: https://quii.gitbook.io/learn-go-with-tests/ y https://apuntes.de/golang/ hay varios

2021-02-09 04:20 UTC, danvergara commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
@zeroidentidad a caray? y por qué sólo @da-edra?

2021-02-09 04:23 UTC, danvergara commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
@4k1k0 Esos githubooks están disponibles de format gratuita en internet. Los libros, vamos a llamarlos regulares, existen en formato físico o digital y es muy probable que haya que pagar por ellos. Sólo creo que son categorías distintas, por la forma de acceder a ellos.

2021-02-09 04:31 UTC, 4k1k0 commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
Dale

2021-02-09 04:41 UTC, zeroidentidad commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
> @zeroidentidad a caray? y por qué sólo @da-edra?

@danvergara pues no sé, quien se vea pueda gestionar los cambios hacer, merge, pertenezca a @gophers-mx

2021-02-09 04:52 UTC, closed without merging

2021-02-09 04:57 UTC, zeroidentidad commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
Bueno, suerte. Hay pueden tomar lo que gusten de lo que deje y hacer sus cambios. Creo hice mal y tomar iniciativa donde no fui llamado  o invitado :v

2021-02-09 23:41 UTC, danvergara commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
Varios puntos que tratar acá @zeroidentidad:

1. No había necesidad de cerrar este pull request, todo su contenido es de mucho valor para la comunidad
2. No necesitas invitación para para contribuir a los proyectos de esta comunidad, ese no fue el problema
3. Se te hizo una sugerencia y tu respuesta fue grosera y arrogante, creo que nadie (siendo miembro de esta organización o no) se merece esa respuesta
4. La sugerencia era para mejorar tu contribución porque añadiste una nueva categoría

Por mí puedes abrir otra vez el PR y esperamos más participación de tu parte, eso sí, con respeto y seriedad para los miembros de esta comunidad.

2021-02-10 02:14 UTC, zeroidentidad commented on README.md
> +| [Apuntes de Golang](https://apuntes.de/golang/) | Curso documentado de Golang | Español |
![134951626_1645592188946607_8055939370860910836_n](https://user-images.githubusercontent.com/2924638/107454829-5afcce00-6b13-11eb-96a8-3c0e3becac9d.png)